let DATA = null;

const COORDS = {
  // North Kerala (Malabar)
  'Kannur':             [11.8745, 75.3704],
  'Kasaragod':          [12.4996, 74.9869],
  'Kozhikode':          [11.2588, 75.7804],
  'Malappuram':         [11.0410, 76.0788],
  'Palakkad':           [10.7867, 76.6548],
  'Wayanad':            [11.6854, 76.1320],
  // South Kerala
  'Alappuzha':          [ 9.4981, 76.3388],
  'Idukki':             [ 9.8560, 76.9744],
  'Kollam':             [ 8.8932, 76.6141],
  'Kottayam':           [ 9.5916, 76.5222],
  'Pathanamthitta':     [ 9.2648, 76.7870],
  'Thiruvananthapuram': [ 8.5241, 76.9366]
};

const COLOR = {red:'#c0392b', yellow:'#e6a817', green:'#4a9d5f'};
const BADGE = {red:'badge-red', yellow:'badge-yellow', green:'badge-green'};
const PCOL  = {4:'#b91c1c',3:'#92400e',2:'#854d0e',1:'#166534',0:'#94a3b8'};
const CHART_COLORS = ['#3b82f6','#ef4444','#10b981','#f59e0b','#8b5cf6','#ec4899','#14b8a6','#64748b'];

let currentWeek = null;
let currentDist = 'Palakkad';
let currentAlertTab = 'sms';
let chartInst   = null;
function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function shortenAction(text) {
  const cleaned = String(text || '').replace(/\s+/g, ' ').trim();
  if(cleaned.length <= 90) return cleaned;
  return cleaned.slice(0, 87).trimEnd() + '...';
}

function getCurrentAlertContext() {
  const d = DATA.warnings[currentWeek][currentDist];
  const weekNumber = String(currentWeek).replace(/\D/g, '');
  return {
    district: currentDist,
    status: d.status,
    disease: d.disease !== '-' ? d.disease : 'Infectious Surveillance',
    cases: d.cases > 0 ? d.cases : 0,
    action: d.recommendation || 'Continue routine monitoring.',
    weekNumber
  };
}

function buildSmsMessage(ctx) {
  return `[KERALA DPH ALERT] ${ctx.status.toUpperCase()} for ${ctx.district}. ${ctx.disease} (${ctx.cases} case(s)) in Week ${ctx.weekNumber}. Action: ${shortenAction(ctx.action)}. Helpline: 1056. Ref:#OBD-Week${ctx.weekNumber}`;
}

function buildWhatsAppMessage(ctx) {
  return [
    `⚠️ ${ctx.status.toUpperCase()} ADVISORY`,
    `*District:* ${ctx.district}`,
    `*Alert Level:* ${ctx.status}`,
    `*Primary Trigger:* ${ctx.disease} (${ctx.cases} case(s))`,
    `*Period:* Week ${ctx.weekNumber}`,
    '',
    `*Recommended Action:*`,
    ctx.action,
    '',
    '_Generated by AI Outbreak Detection System (Malabar Network)_'
  ].join('\n');
}

function renderWhatsAppBody(text) {
  const lines = text.split('\n');
  return lines.map(line => {
    const trimmed = line.trim();
    if(trimmed.startsWith('*') && trimmed.endsWith('*')) {
      return `<div><strong>${escapeHtml(trimmed.slice(1, -1))}</strong></div>`;
    }
    if(trimmed.startsWith('_') && trimmed.endsWith('_')) {
      return `<div><em>${escapeHtml(trimmed.slice(1, -1))}</em></div>`;
    }
    return `<div>${escapeHtml(trimmed || '&nbsp;')}</div>`;
  }).join('');
}

function updateCitizenAlert() {
  const ctx = getCurrentAlertContext();
  const smsText = buildSmsMessage(ctx);
  const waText = buildWhatsAppMessage(ctx);
  const smsChars = smsText.length;
  const smsSegments = Math.max(1, Math.ceil(smsChars / 153));

  document.getElementById('smsMessage').textContent = smsText;
  document.getElementById('smsMeta').textContent = `${smsChars} chars | ${smsSegments} SMS segment(s)`;
  document.getElementById('whatsappMessage').innerHTML = renderWhatsAppBody(waText);
  document.getElementById('whatsappTime').textContent = new Date().toLocaleTimeString([], {hour:'numeric', minute:'2-digit'});
}

function setActiveAlertTab(tabName) {
  currentAlertTab = tabName;
  document.querySelectorAll('.tab-btn').forEach(btn => btn.classList.toggle('active', btn.getAttribute('data-tab') === tabName));
  document.getElementById('smsPreviewPanel').hidden = tabName !== 'sms';
  document.getElementById('whatsappPreviewPanel').hidden = tabName !== 'whatsapp';
}

function appendDispatchLog() {
  const ctx = getCurrentAlertContext();
  const log = document.getElementById('dispatchLog');
  const stamp = new Date().toLocaleString();
  const entry = `${stamp} | ${ctx.district} | ${ctx.status}`;
  const defaultText = 'No alerts dispatched in this session yet. Click "Send Alert Broadcast" above to test.';
  log.value = (log.value.trim() === defaultText ? '' : `${log.value}\n`) + entry;
}

// ── Chart ─────────────────────────────────────────────────────────────────────
